image: atlassian/default-image:2

pipelines:
    branches:
      main:
        - step:
           script:
             - git remote add sync git@github.com:miyabilink/sukkiri-javap2-codes.git
             - git checkout main
             - git pull
             - git merge origin/main
             - git filter-branch -f --env-filter "GIT_AUTHOR_NAME='Gakuto OE'; GIT_AUTHOR_EMAIL='ohe@miyabilink.jp'; GIT_COMMITTER_NAME='Gakuto OE'; GIT_COMMITTER_EMAIL='ohe@miyabilink.jp';" --tag-name-filter cat -- --all
             - git push sync --tags
             - git push -f sync main
